packages:
  - apps/api
  - apps/desktop
  - packages/*
allowBuilds:
  '@nestjs/core': false
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/sdk@1.30.1'
