-- Add the tenant department hierarchy and management metadata.
CREATE TYPE "DepartmentStatus" AS ENUM ('ACTIVE', 'DISABLED');

ALTER TABLE "departments"
    ADD COLUMN "normalized_name" TEXT,
    ADD COLUMN "description" TEXT,
    ADD COLUMN "sort_order" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN "status" "DepartmentStatus" NOT NULL DEFAULT 'ACTIVE';

UPDATE "departments"
SET "normalized_name" = lower(regexp_replace(btrim("name"), '\s+', ' ', 'g'));

ALTER TABLE "departments"
    ALTER COLUMN "normalized_name" SET NOT NULL;

ALTER TABLE "departments"
    ADD CONSTRAINT "departments_parent_id_fkey"
    FOREIGN KEY ("parent_id") REFERENCES "departments"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "departments_tenant_id_status_sort_order_idx"
    ON "departments"("tenant_id", "status", "sort_order");

CREATE UNIQUE INDEX "departments_tenant_parent_name_active_key"
    ON "departments"("tenant_id", "parent_id", "normalized_name")
    WHERE "deleted_at" IS NULL AND "parent_id" IS NOT NULL;

CREATE UNIQUE INDEX "departments_tenant_root_name_active_key"
    ON "departments"("tenant_id", "normalized_name")
    WHERE "deleted_at" IS NULL AND "parent_id" IS NULL;

-- Register department permissions and grant them to every built-in tenant administrator role.
INSERT INTO "permissions" ("id", "code", "name", "created_at", "updated_at")
VALUES
    ('f0000000-0000-0000-0000-000000000010', 'department.read', '查看租户部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('f0000000-0000-0000-0000-000000000011', 'department.create', '创建租户部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('f0000000-0000-0000-0000-000000000012', 'department.update', '修改租户部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('f0000000-0000-0000-0000-000000000013', 'department.delete', '删除租户部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('f0000000-0000-0000-0000-000000000014', 'department.member.assign', '调整成员所属部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO UPDATE SET "name" = EXCLUDED."name", "updated_at" = CURRENT_TIMESTAMP;

INSERT INTO "role_permissions" ("id", "tenant_id", "role_id", "permission_id", "created_at")
SELECT
    md5(role."id"::text || permission."id"::text)::uuid,
    role."tenant_id",
    role."id",
    permission."id",
    CURRENT_TIMESTAMP
FROM "roles" role
JOIN "permissions" permission ON permission."code" IN (
    'department.read',
    'department.create',
    'department.update',
    'department.delete',
    'department.member.assign'
)
WHERE role."code" = 'tenant_admin' AND role."deleted_at" IS NULL
ON CONFLICT ("tenant_id", "role_id", "permission_id") DO NOTHING;

-- Database comments are generated from the maintained database dictionary.
COMMENT ON TABLE "tenants" IS '租户主表，是租户级业务数据的逻辑边界。';
COMMENT ON COLUMN "tenants"."id" IS '租户 UUID';
COMMENT ON COLUMN "tenants"."code" IS '全局唯一租户编码，用于租户登录';
COMMENT ON COLUMN "tenants"."name" IS '租户展示名称';
COMMENT ON COLUMN "tenants"."status" IS 'PENDING_ACTIVATION/ACTIVE/SUSPENDED';
COMMENT ON COLUMN "tenants"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "tenants"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "tenants"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "tenants"."version" IS '租户乐观锁版本';
COMMENT ON TABLE "users" IS '全局人员身份表。一个 User 可以通过多个 Membership 加入多个租户，也可以关联平台管理员身份。';
COMMENT ON COLUMN "users"."id" IS '全局人员 UUID';
COMMENT ON COLUMN "users"."email" IS '兼容阶段保留的可选邮箱，当前账号登录不依赖它';
COMMENT ON COLUMN "users"."normalized_email" IS '规范化邮箱，兼容字段，全局唯一且可空';
COMMENT ON COLUMN "users"."password_hash" IS '兼容阶段保留的可选密码 Hash，当前租户认证不依赖它';
COMMENT ON COLUMN "users"."display_name" IS '全局展示名称';
COMMENT ON COLUMN "users"."status" IS '全局人员状态 ACTIVE/LOCKED/DISABLED';
COMMENT ON COLUMN "users"."failed_login_count" IS '兼容的全局失败次数';
COMMENT ON COLUMN "users"."locked_until" IS '兼容的全局锁定截止时间';
COMMENT ON COLUMN "users"."last_login_at" IS '兼容的全局最后登录时间';
COMMENT ON COLUMN "users"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "users"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "users"."created_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "users"."updated_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "users"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "users"."version" IS '人员版本';
COMMENT ON TABLE "tenant_memberships" IS '用户加入某一租户后的真实成员身份，也是租户账号和租户凭证的保存位置。';
COMMENT ON COLUMN "tenant_memberships"."id" IS 'Membership UUID；JWT 中的 mid 使用该值';
COMMENT ON COLUMN "tenant_memberships"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "tenant_memberships"."user_id" IS '对应全局 User';
COMMENT ON COLUMN "tenant_memberships"."department_id" IS '所属部门，可空';
COMMENT ON COLUMN "tenant_memberships"."display_name" IS '租户内展示名称，可覆盖 User 展示名';
COMMENT ON COLUMN "tenant_memberships"."account" IS '用户输入和展示的租户账号';
COMMENT ON COLUMN "tenant_memberships"."normalized_account" IS '小写规范化账号；与 tenant_id 组合唯一';
COMMENT ON COLUMN "tenant_memberships"."password_hash" IS '租户账号密码 Hash；待激活时可空';
COMMENT ON COLUMN "tenant_memberships"."status" IS 'PENDING_ACTIVATION/ACTIVE/DISABLED';
COMMENT ON COLUMN "tenant_memberships"."failed_login_count" IS '该租户账号连续失败次数';
COMMENT ON COLUMN "tenant_memberships"."locked_until" IS '该租户账号锁定截止时间';
COMMENT ON COLUMN "tenant_memberships"."last_login_at" IS '该租户账号最后成功登录时间';
COMMENT ON COLUMN "tenant_memberships"."joined_at" IS '加入租户时间';
COMMENT ON COLUMN "tenant_memberships"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "tenant_memberships"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "tenant_memberships"."created_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "tenant_memberships"."updated_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "tenant_memberships"."deleted_at" IS '被移出租户的软删除时间';
COMMENT ON COLUMN "tenant_memberships"."version" IS '成员乐观锁版本';
COMMENT ON TABLE "auth_sessions" IS '租户登录会话表，用于 Refresh Token 轮换和即时撤销 Access Token 对应会话。';
COMMENT ON COLUMN "auth_sessions"."id" IS 'Session UUID；JWT 中的 sid 使用该值';
COMMENT ON COLUMN "auth_sessions"."tenant_id" IS '会话租户';
COMMENT ON COLUMN "auth_sessions"."user_id" IS '会话全局用户';
COMMENT ON COLUMN "auth_sessions"."membership_id" IS '会话租户成员';
COMMENT ON COLUMN "auth_sessions"."refresh_token_hash" IS 'Refresh Token Hash，全局唯一';
COMMENT ON COLUMN "auth_sessions"."device_name" IS '登录设备名称';
COMMENT ON COLUMN "auth_sessions"."ip_address" IS '登录或刷新时 IP';
COMMENT ON COLUMN "auth_sessions"."user_agent" IS '客户端 User-Agent';
COMMENT ON COLUMN "auth_sessions"."expires_at" IS 'Refresh Session 过期时间';
COMMENT ON COLUMN "auth_sessions"."last_used_at" IS '最近刷新使用时间';
COMMENT ON COLUMN "auth_sessions"."revoked_at" IS '撤销时间；非空后 Access Token 也不可继续使用';
COMMENT ON COLUMN "auth_sessions"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "auth_sessions"."updated_at" IS '创建和更新时间';
COMMENT ON TABLE "platform_administrators" IS '平台管理员账号表。查询“平台管理员账号”时重点查看本表，并关联 users 获取展示名称。';
COMMENT ON COLUMN "platform_administrators"."id" IS '平台管理员 UUID';
COMMENT ON COLUMN "platform_administrators"."user_id" IS '一对一关联的全局 User UUID';
COMMENT ON COLUMN "platform_administrators"."account" IS '平台账号原始值';
COMMENT ON COLUMN "platform_administrators"."normalized_account" IS '小写规范化账号，全局唯一';
COMMENT ON COLUMN "platform_administrators"."password_hash" IS '平台密码 Hash';
COMMENT ON COLUMN "platform_administrators"."role" IS '当前为 SUPER_ADMIN';
COMMENT ON COLUMN "platform_administrators"."status" IS 'ACTIVE 或 DISABLED';
COMMENT ON COLUMN "platform_administrators"."failed_login_count" IS '平台登录连续失败次数';
COMMENT ON COLUMN "platform_administrators"."locked_until" IS '平台账号锁定截止时间';
COMMENT ON COLUMN "platform_administrators"."last_login_at" IS '平台最后成功登录时间';
COMMENT ON COLUMN "platform_administrators"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "platform_administrators"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "platform_administrators"."created_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "platform_administrators"."updated_by" IS '创建和修改者 UUID';
COMMENT ON COLUMN "platform_administrators"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "platform_administrators"."version" IS '平台管理员版本';
COMMENT ON TABLE "platform_auth_sessions" IS '平台管理员独立 Session 表，不与租户 auth_sessions 混用。';
COMMENT ON COLUMN "platform_auth_sessions"."id" IS '平台 Session UUID';
COMMENT ON COLUMN "platform_auth_sessions"."platform_administrator_id" IS '平台管理员 UUID';
COMMENT ON COLUMN "platform_auth_sessions"."user_id" IS '对应全局 User UUID';
COMMENT ON COLUMN "platform_auth_sessions"."refresh_token_hash" IS '平台 Refresh Token Hash';
COMMENT ON COLUMN "platform_auth_sessions"."device_name" IS '登录客户端信息';
COMMENT ON COLUMN "platform_auth_sessions"."ip_address" IS '登录客户端信息';
COMMENT ON COLUMN "platform_auth_sessions"."user_agent" IS '登录客户端信息';
COMMENT ON COLUMN "platform_auth_sessions"."expires_at" IS 'Session 过期时间';
COMMENT ON COLUMN "platform_auth_sessions"."last_used_at" IS '最近刷新时间';
COMMENT ON COLUMN "platform_auth_sessions"."revoked_at" IS '撤销时间';
COMMENT ON COLUMN "platform_auth_sessions"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "platform_auth_sessions"."updated_at" IS '创建和更新时间';
COMMENT ON TABLE "departments" IS '租户组织部门树，通过 parent_id 自关联并由公开部门管理 API 维护。';
COMMENT ON COLUMN "departments"."id" IS '部门 UUID';
COMMENT ON COLUMN "departments"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "departments"."parent_id" IS '父部门 UUID；为空表示根部门';
COMMENT ON COLUMN "departments"."name" IS '部门名称';
COMMENT ON COLUMN "departments"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "departments"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "departments"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "departments"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "departments"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "departments"."version" IS '部门版本';
COMMENT ON TABLE "tenant_invitations" IS '租户成员首次激活、首位管理员激活和凭证重置共用的一次性邀请记录。';
COMMENT ON COLUMN "tenant_invitations"."id" IS '邀请 UUID';
COMMENT ON COLUMN "tenant_invitations"."tenant_id" IS '目标租户';
COMMENT ON COLUMN "tenant_invitations"."account" IS '为成员预留的账号';
COMMENT ON COLUMN "tenant_invitations"."normalized_account" IS '小写规范化账号，用于冲突检查';
COMMENT ON COLUMN "tenant_invitations"."display_name" IS '被邀请人的展示名称';
COMMENT ON COLUMN "tenant_invitations"."target_membership_id" IS '凭证重置时指向已有 Membership；新成员邀请为空';
COMMENT ON COLUMN "tenant_invitations"."token_hash" IS '一次性邀请令牌 Hash，全局唯一';
COMMENT ON COLUMN "tenant_invitations"."status" IS 'PENDING/ACCEPTED/REVOKED/EXPIRED';
COMMENT ON COLUMN "tenant_invitations"."is_initial_administrator" IS '是否为租户首位管理员邀请';
COMMENT ON COLUMN "tenant_invitations"."expires_at" IS '邀请过期时间';
COMMENT ON COLUMN "tenant_invitations"."accepted_at" IS '接受时间';
COMMENT ON COLUMN "tenant_invitations"."accepted_by_user_id" IS '最终接受邀请的 User UUID';
COMMENT ON COLUMN "tenant_invitations"."invited_by_user_id" IS '发起邀请的 User UUID；平台创建租户时记录平台操作者对应 User';
COMMENT ON COLUMN "tenant_invitations"."revoked_at" IS '撤销时间';
COMMENT ON COLUMN "tenant_invitations"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "tenant_invitations"."updated_at" IS '创建和更新时间';
COMMENT ON TABLE "tenant_invitation_roles" IS '邀请与待分配角色的多对多关系。';
COMMENT ON COLUMN "tenant_invitation_roles"."id" IS '关系 UUID';
COMMENT ON COLUMN "tenant_invitation_roles"."invitation_id" IS '邀请 UUID';
COMMENT ON COLUMN "tenant_invitation_roles"."role_id" IS '激活后要分配的角色 UUID';
COMMENT ON COLUMN "tenant_invitation_roles"."created_at" IS '创建时间';
COMMENT ON TABLE "permissions" IS '平台预置的租户权限目录。';
COMMENT ON COLUMN "permissions"."id" IS '权限 UUID';
COMMENT ON COLUMN "permissions"."code" IS '全局唯一权限编码，如 member.read';
COMMENT ON COLUMN "permissions"."name" IS '权限中文名称';
COMMENT ON COLUMN "permissions"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "permissions"."updated_at" IS '创建和更新时间';
COMMENT ON TABLE "roles" IS '租户角色表，包含系统角色和租户自定义角色。';
COMMENT ON COLUMN "roles"."id" IS '角色 UUID';
COMMENT ON COLUMN "roles"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "roles"."code" IS '租户内唯一稳定编码';
COMMENT ON COLUMN "roles"."name" IS '展示名称';
COMMENT ON COLUMN "roles"."description" IS '角色说明';
COMMENT ON COLUMN "roles"."is_system" IS '是否系统角色；tenant_admin 为 true';
COMMENT ON COLUMN "roles"."data_scope" IS '数据范围 DataScope';
COMMENT ON COLUMN "roles"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "roles"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "roles"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "roles"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "roles"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "roles"."version" IS '角色乐观锁版本';
COMMENT ON TABLE "membership_roles" IS '租户成员和角色的多对多关系，是判断“某成员是否为租户管理员”的关键表。';
COMMENT ON COLUMN "membership_roles"."id" IS '关系 UUID';
COMMENT ON COLUMN "membership_roles"."tenant_id" IS '冗余租户边界，防止跨租户关联';
COMMENT ON COLUMN "membership_roles"."membership_id" IS '租户成员 UUID';
COMMENT ON COLUMN "membership_roles"."role_id" IS '角色 UUID';
COMMENT ON COLUMN "membership_roles"."created_at" IS '分配时间';
COMMENT ON TABLE "role_permissions" IS '租户角色和权限的多对多关系。';
COMMENT ON COLUMN "role_permissions"."id" IS '关系 UUID';
COMMENT ON COLUMN "role_permissions"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "role_permissions"."role_id" IS '角色 UUID';
COMMENT ON COLUMN "role_permissions"."permission_id" IS '权限 UUID';
COMMENT ON COLUMN "role_permissions"."created_at" IS '分配时间';
COMMENT ON TABLE "resources" IS '统一资源授权根。当前资源类型只有 DOCUMENT。';
COMMENT ON COLUMN "resources"."id" IS 'Resource UUID；与对应 managed_documents.id 相同';
COMMENT ON COLUMN "resources"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "resources"."type" IS '资源类型，当前为 DOCUMENT';
COMMENT ON COLUMN "resources"."owner_membership_id" IS '资源所有者 Membership UUID';
COMMENT ON COLUMN "resources"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "resources"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "resources"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "resources"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "resources"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "resources"."version" IS '资源版本';
COMMENT ON TABLE "managed_documents" IS '已经开放公开 API 的受控文档表，不要与知识库的 documents 表混淆。';
COMMENT ON COLUMN "managed_documents"."id" IS '文档 UUID，同时引用 resources.id';
COMMENT ON COLUMN "managed_documents"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "managed_documents"."title" IS '文档标题';
COMMENT ON COLUMN "managed_documents"."content" IS '文档正文文本';
COMMENT ON COLUMN "managed_documents"."visibility" IS 'PRIVATE 或 TENANT';
COMMENT ON COLUMN "managed_documents"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "managed_documents"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "managed_documents"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "managed_documents"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "managed_documents"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "managed_documents"."version" IS '文档乐观锁版本';
COMMENT ON TABLE "resource_acls" IS '资源级授权表。ACL 只能扩展资源范围，不能绕过角色的 RBAC 操作权限。';
COMMENT ON COLUMN "resource_acls"."id" IS 'ACL UUID';
COMMENT ON COLUMN "resource_acls"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "resource_acls"."resource_id" IS '被授权 Resource UUID';
COMMENT ON COLUMN "resource_acls"."subject_type" IS 'MEMBERSHIP 或 ROLE';
COMMENT ON COLUMN "resource_acls"."subject_id" IS '对应成员或角色 UUID';
COMMENT ON COLUMN "resource_acls"."permission_codes" IS 'PostgreSQL 字符串数组，保存文档权限编码';
COMMENT ON COLUMN "resource_acls"."expires_at" IS '授权过期时间；为空表示长期有效';
COMMENT ON COLUMN "resource_acls"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "resource_acls"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "resource_acls"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "resource_acls"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "resource_acls"."deleted_at" IS '随资源软删除时使用；正常撤销 ACL 为硬删除';
COMMENT ON COLUMN "resource_acls"."version" IS 'ACL 乐观锁版本';
COMMENT ON TABLE "projects" IS '项目主表。';
COMMENT ON COLUMN "projects"."id" IS '项目 UUID';
COMMENT ON COLUMN "projects"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "projects"."department_id" IS '所属部门 UUID，可空';
COMMENT ON COLUMN "projects"."name" IS '项目名称';
COMMENT ON COLUMN "projects"."description" IS '项目说明';
COMMENT ON COLUMN "projects"."status" IS '项目状态字符串，当前默认 ACTIVE，尚未形成公开枚举契约';
COMMENT ON COLUMN "projects"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "projects"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "projects"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "projects"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "projects"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "projects"."version" IS '项目版本';
COMMENT ON TABLE "project_members" IS '项目和用户的成员关系。';
COMMENT ON COLUMN "project_members"."id" IS '关系 UUID';
COMMENT ON COLUMN "project_members"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "project_members"."project_id" IS '项目 UUID';
COMMENT ON COLUMN "project_members"."user_id" IS '成员 User UUID';
COMMENT ON COLUMN "project_members"."role" IS '项目内角色字符串，默认 MEMBER';
COMMENT ON COLUMN "project_members"."created_at" IS '加入项目时间';
COMMENT ON TABLE "tasks" IS '任务主表，支持项目任务、父子任务、优先级、截止时间和通用业务关联。';
COMMENT ON COLUMN "tasks"."id" IS '任务 UUID';
COMMENT ON COLUMN "tasks"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "tasks"."project_id" IS '所属项目 UUID，可空';
COMMENT ON COLUMN "tasks"."parent_id" IS '父任务 UUID，可空';
COMMENT ON COLUMN "tasks"."title" IS '任务标题';
COMMENT ON COLUMN "tasks"."description" IS '任务说明';
COMMENT ON COLUMN "tasks"."status" IS 'TODO/IN_PROGRESS/BLOCKED/DONE/CANCELLED';
COMMENT ON COLUMN "tasks"."priority" IS 'LOW/MEDIUM/HIGH/URGENT';
COMMENT ON COLUMN "tasks"."due_date" IS '截止时间';
COMMENT ON COLUMN "tasks"."relation_type" IS '外部业务关联类型';
COMMENT ON COLUMN "tasks"."relation_id" IS '外部业务关联资源 UUID';
COMMENT ON COLUMN "tasks"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "tasks"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "tasks"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "tasks"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "tasks"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "tasks"."version" IS '任务版本';
COMMENT ON TABLE "task_assignees" IS '任务和执行人的多对多关系。';
COMMENT ON COLUMN "task_assignees"."id" IS '分配 UUID';
COMMENT ON COLUMN "task_assignees"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "task_assignees"."task_id" IS '任务 UUID';
COMMENT ON COLUMN "task_assignees"."user_id" IS '执行人 User UUID';
COMMENT ON COLUMN "task_assignees"."assignee_type" IS '执行人类型字符串，默认 OWNER';
COMMENT ON COLUMN "task_assignees"."created_at" IS '分配时间';
COMMENT ON TABLE "task_comments" IS '任务评论表。';
COMMENT ON COLUMN "task_comments"."id" IS '评论 UUID';
COMMENT ON COLUMN "task_comments"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "task_comments"."task_id" IS '任务 UUID';
COMMENT ON COLUMN "task_comments"."content" IS '评论内容';
COMMENT ON COLUMN "task_comments"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "task_comments"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "task_comments"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "task_comments"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "task_comments"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "task_comments"."version" IS '评论版本';
COMMENT ON TABLE "task_attachments" IS '任务和文件对象的关联表。';
COMMENT ON COLUMN "task_attachments"."id" IS '附件关系 UUID';
COMMENT ON COLUMN "task_attachments"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "task_attachments"."task_id" IS '任务 UUID';
COMMENT ON COLUMN "task_attachments"."file_object_id" IS '文件对象 UUID';
COMMENT ON COLUMN "task_attachments"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "task_attachments"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "task_attachments"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "task_attachments"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "task_attachments"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "task_attachments"."version" IS '附件关系版本';
COMMENT ON TABLE "task_activities" IS '任务领域活动流水，与全局安全审计的 audit_logs 用途不同。';
COMMENT ON COLUMN "task_activities"."id" IS '活动 UUID';
COMMENT ON COLUMN "task_activities"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "task_activities"."task_id" IS '任务 UUID';
COMMENT ON COLUMN "task_activities"."action" IS '任务动作编码';
COMMENT ON COLUMN "task_activities"."metadata" IS '动作扩展 JSON';
COMMENT ON COLUMN "task_activities"."created_at" IS '发生时间';
COMMENT ON COLUMN "task_activities"."created_by" IS '操作者 User UUID';
COMMENT ON TABLE "file_objects" IS '文件元数据表。二进制内容不进入 PostgreSQL，正式设计中存放于私有 COS。';
COMMENT ON COLUMN "file_objects"."id" IS '文件对象 UUID';
COMMENT ON COLUMN "file_objects"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "file_objects"."object_key" IS 'COS 对象键，不是公开下载 URL';
COMMENT ON COLUMN "file_objects"."mime_type" IS 'MIME 类型';
COMMENT ON COLUMN "file_objects"."size_bytes" IS '文件字节数';
COMMENT ON COLUMN "file_objects"."checksum" IS '文件校验值，可空';
COMMENT ON COLUMN "file_objects"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "file_objects"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "file_objects"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "file_objects"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "file_objects"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "file_objects"."version" IS '文件元数据版本';
COMMENT ON TABLE "knowledge_bases" IS '知识库主表，目前没有公开管理 API。';
COMMENT ON COLUMN "knowledge_bases"."id" IS '知识库 UUID';
COMMENT ON COLUMN "knowledge_bases"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "knowledge_bases"."name" IS '知识库名称';
COMMENT ON COLUMN "knowledge_bases"."description" IS '知识库说明';
COMMENT ON COLUMN "knowledge_bases"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "knowledge_bases"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "knowledge_bases"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "knowledge_bases"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "knowledge_bases"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "knowledge_bases"."version" IS '知识库版本';
COMMENT ON TABLE "knowledge_base_members" IS '知识库与用户的授权关系。';
COMMENT ON COLUMN "knowledge_base_members"."id" IS '关系 UUID';
COMMENT ON COLUMN "knowledge_base_members"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "knowledge_base_members"."knowledge_base_id" IS '知识库 UUID';
COMMENT ON COLUMN "knowledge_base_members"."user_id" IS 'User UUID';
COMMENT ON COLUMN "knowledge_base_members"."permission" IS '知识库权限字符串，尚未形成公开枚举契约';
COMMENT ON COLUMN "knowledge_base_members"."created_at" IS '创建时间';
COMMENT ON TABLE "documents" IS '知识库文档表，对应 Prisma 模型 KnowledgeDocument。它与已经开放 API 的 managed_documents 是两个不同概念。';
COMMENT ON COLUMN "documents"."id" IS '知识文档 UUID';
COMMENT ON COLUMN "documents"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "documents"."knowledge_base_id" IS '所属知识库 UUID';
COMMENT ON COLUMN "documents"."file_object_id" IS '原始文件对象 UUID';
COMMENT ON COLUMN "documents"."name" IS '文档名称';
COMMENT ON COLUMN "documents"."status" IS '处理状态字符串，默认 PENDING';
COMMENT ON COLUMN "documents"."department_id" IS '可见部门 UUID，可空';
COMMENT ON COLUMN "documents"."project_id" IS '可见项目 UUID，可空';
COMMENT ON COLUMN "documents"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "documents"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "documents"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "documents"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "documents"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "documents"."version" IS '知识文档版本';
COMMENT ON TABLE "document_versions" IS '知识文档文件版本表。';
COMMENT ON COLUMN "document_versions"."id" IS '版本记录 UUID';
COMMENT ON COLUMN "document_versions"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "document_versions"."document_id" IS '知识文档 UUID';
COMMENT ON COLUMN "document_versions"."file_object_id" IS '该版本对应文件对象 UUID';
COMMENT ON COLUMN "document_versions"."version_number" IS '文档内部版本号';
COMMENT ON COLUMN "document_versions"."created_at" IS '版本创建时间';
COMMENT ON COLUMN "document_versions"."created_by" IS '创建者 User UUID';
COMMENT ON TABLE "document_chunks" IS '知识文档切片和向量检索数据表。';
COMMENT ON COLUMN "document_chunks"."id" IS 'Chunk UUID';
COMMENT ON COLUMN "document_chunks"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "document_chunks"."knowledge_base_id" IS '所属知识库 UUID';
COMMENT ON COLUMN "document_chunks"."document_id" IS '来源知识文档 UUID';
COMMENT ON COLUMN "document_chunks"."department_id" IS '部门过滤维度，可空';
COMMENT ON COLUMN "document_chunks"."project_id" IS '项目过滤维度，可空';
COMMENT ON COLUMN "document_chunks"."visibility_scope" IS 'PRIVATE/DEPARTMENT/PROJECT/TENANT/CUSTOM';
COMMENT ON COLUMN "document_chunks"."content" IS '切片文本';
COMMENT ON COLUMN "document_chunks"."embedding" IS 'pgvector 向量字段，Prisma 使用 Unsupported(vector) 映射';
COMMENT ON COLUMN "document_chunks"."metadata" IS '切片扩展 JSON';
COMMENT ON COLUMN "document_chunks"."chunk_index" IS '在原文档中的切片顺序';
COMMENT ON COLUMN "document_chunks"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "document_chunks"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "document_chunks"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "document_chunks"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "document_chunks"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "document_chunks"."version" IS 'Chunk 版本';
COMMENT ON TABLE "knowledge_query_logs" IS '知识检索问答日志。';
COMMENT ON COLUMN "knowledge_query_logs"."id" IS '查询日志 UUID';
COMMENT ON COLUMN "knowledge_query_logs"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "knowledge_query_logs"."user_id" IS '发起查询的 User UUID';
COMMENT ON COLUMN "knowledge_query_logs"."query" IS '用户问题';
COMMENT ON COLUMN "knowledge_query_logs"."answer" IS '最终回答，可空';
COMMENT ON COLUMN "knowledge_query_logs"."citations" IS '引用信息 JSON，可空';
COMMENT ON COLUMN "knowledge_query_logs"."request_id" IS '请求追踪 ID';
COMMENT ON COLUMN "knowledge_query_logs"."created_at" IS '查询时间';
COMMENT ON TABLE "meetings" IS '会议主表，目前没有公开 API。';
COMMENT ON COLUMN "meetings"."id" IS '会议 UUID';
COMMENT ON COLUMN "meetings"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "meetings"."title" IS '会议标题';
COMMENT ON COLUMN "meetings"."starts_at" IS '开始时间';
COMMENT ON COLUMN "meetings"."duration_minutes" IS '预计时长，单位分钟';
COMMENT ON COLUMN "meetings"."department_id" IS '所属部门 UUID，可空';
COMMENT ON COLUMN "meetings"."agenda" IS '会议议程 JSON';
COMMENT ON COLUMN "meetings"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "meetings"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "meetings"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "meetings"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "meetings"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "meetings"."version" IS '会议版本';
COMMENT ON TABLE "meeting_participants" IS '会议参会人关系。';
COMMENT ON COLUMN "meeting_participants"."id" IS '关系 UUID';
COMMENT ON COLUMN "meeting_participants"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "meeting_participants"."meeting_id" IS '会议 UUID';
COMMENT ON COLUMN "meeting_participants"."user_id" IS '参会人 User UUID';
COMMENT ON COLUMN "meeting_participants"."status" IS '参会状态字符串，默认 INVITED';
COMMENT ON COLUMN "meeting_participants"."created_at" IS '邀请或加入时间';
COMMENT ON TABLE "meeting_minutes" IS '会议纪要表。';
COMMENT ON COLUMN "meeting_minutes"."id" IS '纪要 UUID';
COMMENT ON COLUMN "meeting_minutes"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "meeting_minutes"."meeting_id" IS '会议 UUID';
COMMENT ON COLUMN "meeting_minutes"."content" IS '结构化纪要 JSON';
COMMENT ON COLUMN "meeting_minutes"."status" IS '纪要状态字符串，默认 DRAFT';
COMMENT ON COLUMN "meeting_minutes"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "meeting_minutes"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "meeting_minutes"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "meeting_minutes"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "meeting_minutes"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "meeting_minutes"."version" IS '纪要版本';
COMMENT ON TABLE "notifications" IS '通知内容主表。';
COMMENT ON COLUMN "notifications"."id" IS '通知 UUID';
COMMENT ON COLUMN "notifications"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "notifications"."title" IS '通知标题';
COMMENT ON COLUMN "notifications"."content" IS '通知正文';
COMMENT ON COLUMN "notifications"."channel" IS '通知渠道字符串，默认 IN_APP';
COMMENT ON COLUMN "notifications"."relation_type" IS '关联业务类型';
COMMENT ON COLUMN "notifications"."relation_id" IS '关联业务资源 UUID';
COMMENT ON COLUMN "notifications"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "notifications"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "notifications"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "notifications"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "notifications"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "notifications"."version" IS '通知版本';
COMMENT ON TABLE "notification_recipients" IS '通知和接收用户的关系及阅读状态。';
COMMENT ON COLUMN "notification_recipients"."id" IS '接收关系 UUID';
COMMENT ON COLUMN "notification_recipients"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "notification_recipients"."notification_id" IS '通知 UUID';
COMMENT ON COLUMN "notification_recipients"."user_id" IS '接收人 User UUID';
COMMENT ON COLUMN "notification_recipients"."read_at" IS '阅读时间；为空表示未读';
COMMENT ON COLUMN "notification_recipients"."created_at" IS '投递时间';
COMMENT ON TABLE "ai_action_drafts" IS 'AI 生成的待确认动作草稿。它不是正式业务数据，只有经过 NestJS 权限校验和确认流程后才能执行正式写入。';
COMMENT ON COLUMN "ai_action_drafts"."id" IS '草稿 UUID';
COMMENT ON COLUMN "ai_action_drafts"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "ai_action_drafts"."user_id" IS '发起 AI 请求的 User UUID';
COMMENT ON COLUMN "ai_action_drafts"."action_type" IS '建议执行的动作类型';
COMMENT ON COLUMN "ai_action_drafts"."payload" IS '草稿结构化内容 JSON';
COMMENT ON COLUMN "ai_action_drafts"."status" IS 'DraftStatus';
COMMENT ON COLUMN "ai_action_drafts"."expires_at" IS '草稿失效时间';
COMMENT ON COLUMN "ai_action_drafts"."executed_resource_type" IS '执行后生成的正式资源类型';
COMMENT ON COLUMN "ai_action_drafts"."executed_resource_id" IS '执行后生成的正式资源 UUID';
COMMENT ON COLUMN "ai_action_drafts"."created_at" IS '创建和更新时间';
COMMENT ON COLUMN "ai_action_drafts"."updated_at" IS '创建和更新时间';
COMMENT ON COLUMN "ai_action_drafts"."created_by" IS '创建和修改者';
COMMENT ON COLUMN "ai_action_drafts"."updated_by" IS '创建和修改者';
COMMENT ON COLUMN "ai_action_drafts"."deleted_at" IS '软删除时间';
COMMENT ON COLUMN "ai_action_drafts"."version" IS '草稿版本';
COMMENT ON TABLE "ai_invocation_logs" IS 'NestJS 编排 AI 调用时记录的模型调用指标。';
COMMENT ON COLUMN "ai_invocation_logs"."id" IS '调用日志 UUID';
COMMENT ON COLUMN "ai_invocation_logs"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "ai_invocation_logs"."user_id" IS '发起调用的 User UUID';
COMMENT ON COLUMN "ai_invocation_logs"."request_id" IS '业务请求追踪 ID';
COMMENT ON COLUMN "ai_invocation_logs"."trace_id" IS '跨服务 Trace ID，可空';
COMMENT ON COLUMN "ai_invocation_logs"."model" IS '实际模型名称';
COMMENT ON COLUMN "ai_invocation_logs"."latency_ms" IS '调用耗时，毫秒';
COMMENT ON COLUMN "ai_invocation_logs"."input_tokens" IS '输入和输出 Token 数，可空';
COMMENT ON COLUMN "ai_invocation_logs"."output_tokens" IS '输入和输出 Token 数，可空';
COMMENT ON COLUMN "ai_invocation_logs"."operation" IS 'AI 操作类型';
COMMENT ON COLUMN "ai_invocation_logs"."metadata" IS '扩展指标和路由信息 JSON';
COMMENT ON COLUMN "ai_invocation_logs"."created_at" IS '调用时间';
COMMENT ON TABLE "audit_logs" IS '租户业务审计表。所有查询都必须按 tenant_id 隔离。';
COMMENT ON COLUMN "audit_logs"."id" IS '审计 UUID';
COMMENT ON COLUMN "audit_logs"."tenant_id" IS '所属租户';
COMMENT ON COLUMN "audit_logs"."actor_user_id" IS '操作者全局 User UUID';
COMMENT ON COLUMN "audit_logs"."actor_membership_id" IS '操作者 Membership UUID';
COMMENT ON COLUMN "audit_logs"."action" IS '操作动作编码';
COMMENT ON COLUMN "audit_logs"."outcome" IS 'SUCCESS 或 FAILURE';
COMMENT ON COLUMN "audit_logs"."resource_type" IS '操作资源类型';
COMMENT ON COLUMN "audit_logs"."resource_id" IS '操作资源 UUID，可空';
COMMENT ON COLUMN "audit_logs"."request_id" IS 'HTTP 请求追踪 ID';
COMMENT ON COLUMN "audit_logs"."ip_address" IS '客户端 IP';
COMMENT ON COLUMN "audit_logs"."user_agent" IS '客户端 User-Agent';
COMMENT ON COLUMN "audit_logs"."metadata" IS '操作前后值、原因等扩展 JSON';
COMMENT ON COLUMN "audit_logs"."created_at" IS '审计发生时间';
COMMENT ON TABLE "platform_audit_logs" IS '平台管理审计表，与租户审计分开保存。';
COMMENT ON COLUMN "platform_audit_logs"."id" IS '平台审计 UUID';
COMMENT ON COLUMN "platform_audit_logs"."actor_user_id" IS '平台操作者对应 User UUID';
COMMENT ON COLUMN "platform_audit_logs"."actor_platform_administrator_id" IS '平台管理员 UUID';
COMMENT ON COLUMN "platform_audit_logs"."action" IS '平台动作编码';
COMMENT ON COLUMN "platform_audit_logs"."outcome" IS 'SUCCESS 或 FAILURE';
COMMENT ON COLUMN "platform_audit_logs"."resource_type" IS '平台操作资源类型';
COMMENT ON COLUMN "platform_audit_logs"."resource_id" IS '租户、管理员等资源 UUID';
COMMENT ON COLUMN "platform_audit_logs"."request_id" IS 'HTTP 请求追踪 ID';
COMMENT ON COLUMN "platform_audit_logs"."ip_address" IS '客户端 IP';
COMMENT ON COLUMN "platform_audit_logs"."user_agent" IS '客户端 User-Agent';
COMMENT ON COLUMN "platform_audit_logs"."metadata" IS '停用原因、前后状态等扩展 JSON';
COMMENT ON COLUMN "platform_audit_logs"."created_at" IS '审计发生时间';
COMMENT ON TYPE "DepartmentStatus" IS '部门启用状态：ACTIVE 启用，DISABLED 停用';
COMMENT ON COLUMN "departments"."normalized_name" IS '小写并规范空白后的部门名称，用于同级唯一性校验';
COMMENT ON COLUMN "departments"."description" IS '部门说明，可为空';
COMMENT ON COLUMN "departments"."sort_order" IS '同级部门排序值，数值越小越靠前';
COMMENT ON COLUMN "departments"."status" IS '部门状态：ACTIVE 启用，DISABLED 停用';
