/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum TencentMeetingConnectorErrorCode {
    CONNECTOR_NOT_CONFIGURED = 'CONNECTOR_NOT_CONFIGURED',
    CONNECTOR_ALREADY_CONNECTED = 'CONNECTOR_ALREADY_CONNECTED',
    OAUTH_STATE_INVALID = 'OAUTH_STATE_INVALID',
    OAUTH_STATE_EXPIRED = 'OAUTH_STATE_EXPIRED',
    OAUTH_STATE_ALREADY_USED = 'OAUTH_STATE_ALREADY_USED',
    OAUTH_ACCESS_DENIED = 'OAUTH_ACCESS_DENIED',
    AUTH_REQUIRED = 'AUTH_REQUIRED',
    INSUFFICIENT_SCOPE = 'INSUFFICIENT_SCOPE',
    TOKEN_REFRESH_FAILED = 'TOKEN_REFRESH_FAILED',
    PROVIDER_RATE_LIMITED = 'PROVIDER_RATE_LIMITED',
    PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
    RESOURCE_FORBIDDEN = 'RESOURCE_FORBIDDEN',
    INVALID_ARGUMENTS = 'INVALID_ARGUMENTS',
}
