COMMENT ON TABLE tasks IS '项目任务主表，保存父子层级、状态、优先级和乐观锁版本。';
COMMENT ON COLUMN tasks.id IS '任务 UUID';
COMMENT ON COLUMN tasks.tenant_id IS '所属租户 UUID';
COMMENT ON COLUMN tasks.project_id IS '所属项目 UUID；项目任务接口创建的数据必填';
COMMENT ON COLUMN tasks.parent_id IS '父任务 UUID；为空表示根任务';
COMMENT ON COLUMN tasks.title IS '任务标题';
COMMENT ON COLUMN tasks.description IS '任务详细说明';
COMMENT ON COLUMN tasks.status IS '任务状态 TaskStatus';
COMMENT ON COLUMN tasks.priority IS '任务优先级 TaskPriority';
COMMENT ON COLUMN tasks.due_date IS '计划截止时间';
COMMENT ON COLUMN tasks.relation_type IS '预留的关联业务类型';
COMMENT ON COLUMN tasks.relation_id IS '预留的关联业务资源 UUID';
COMMENT ON COLUMN tasks.created_by_membership_id IS '创建任务的租户成员 UUID';
COMMENT ON COLUMN tasks.created_at IS '创建时间';
COMMENT ON COLUMN tasks.updated_at IS '最后更新时间';
COMMENT ON COLUMN tasks.created_by IS '创建者 User UUID';
COMMENT ON COLUMN tasks.updated_by IS '最后修改者 User UUID';
COMMENT ON COLUMN tasks.deleted_at IS '软删除时间；为空表示有效任务';
COMMENT ON COLUMN tasks.version IS '乐观锁版本，每次写操作递增';

COMMENT ON TABLE task_assignees IS '任务执行人关系表，每个任务只能有一个 OWNER，可有多个 COLLABORATOR。';
COMMENT ON COLUMN task_assignees.id IS '任务执行人关系 UUID';
COMMENT ON COLUMN task_assignees.tenant_id IS '所属租户 UUID';
COMMENT ON COLUMN task_assignees.task_id IS '任务 UUID';
COMMENT ON COLUMN task_assignees.membership_id IS '被分配任务的租户成员 UUID';
COMMENT ON COLUMN task_assignees.assignee_type IS '任务执行人类型：OWNER 或 COLLABORATOR';
COMMENT ON COLUMN task_assignees.created_at IS '分配时间';

COMMENT ON TABLE task_comments IS '任务评论表，评论支持软删除和乐观锁。';
COMMENT ON COLUMN task_comments.id IS '任务评论 UUID';
COMMENT ON COLUMN task_comments.tenant_id IS '所属租户 UUID';
COMMENT ON COLUMN task_comments.task_id IS '任务 UUID';
COMMENT ON COLUMN task_comments.content IS '评论正文';
COMMENT ON COLUMN task_comments.author_membership_id IS '评论作者对应的租户成员 UUID';
COMMENT ON COLUMN task_comments.created_at IS '创建时间';
COMMENT ON COLUMN task_comments.updated_at IS '最后更新时间';
COMMENT ON COLUMN task_comments.created_by IS '创建者 User UUID';
COMMENT ON COLUMN task_comments.updated_by IS '最后修改者 User UUID';
COMMENT ON COLUMN task_comments.deleted_at IS '软删除时间';
COMMENT ON COLUMN task_comments.version IS '评论乐观锁版本';

COMMENT ON TABLE task_attachments IS '任务与腾讯云 COS 文件对象的附件关系表；删除关系不删除文件对象。';
COMMENT ON COLUMN task_attachments.id IS '任务附件关系 UUID';
COMMENT ON COLUMN task_attachments.tenant_id IS '所属租户 UUID';
COMMENT ON COLUMN task_attachments.task_id IS '任务 UUID';
COMMENT ON COLUMN task_attachments.file_object_id IS '已完成上传的文件对象 UUID';
COMMENT ON COLUMN task_attachments.created_by_membership_id IS '添加附件的租户成员 UUID';
COMMENT ON COLUMN task_attachments.created_at IS '创建时间';
COMMENT ON COLUMN task_attachments.updated_at IS '最后更新时间';
COMMENT ON COLUMN task_attachments.created_by IS '创建者 User UUID';
COMMENT ON COLUMN task_attachments.updated_by IS '最后修改者 User UUID';
COMMENT ON COLUMN task_attachments.deleted_at IS '软删除时间';
COMMENT ON COLUMN task_attachments.version IS '附件关系乐观锁版本';

COMMENT ON TABLE task_activities IS '任务操作动态表，记录任务资料、状态、评论、附件和执行人变化。';
COMMENT ON COLUMN task_activities.id IS '任务动态 UUID';
COMMENT ON COLUMN task_activities.tenant_id IS '所属租户 UUID';
COMMENT ON COLUMN task_activities.task_id IS '任务 UUID';
COMMENT ON COLUMN task_activities.action IS '任务动作编码';
COMMENT ON COLUMN task_activities.metadata IS '动作前后状态和关联资源等扩展 JSON';
COMMENT ON COLUMN task_activities.actor_membership_id IS '执行任务动作的租户成员 UUID，可空表示系统动作';
COMMENT ON COLUMN task_activities.created_at IS '动作发生时间';
COMMENT ON COLUMN task_activities.created_by IS '操作者 User UUID';
