/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AcceptTenantInvitationRequest } from './models/AcceptTenantInvitationRequest';
export type { AccountSuggestion } from './models/AccountSuggestion';
export type { AccountSuggestionRequest } from './models/AccountSuggestionRequest';
export type { AccountSuggestionResponseEnvelope } from './models/AccountSuggestionResponseEnvelope';
export { AclSubjectType } from './models/AclSubjectType';
export type { AddMeetingParticipantRequest } from './models/AddMeetingParticipantRequest';
export { AddProjectMemberRequest } from './models/AddProjectMemberRequest';
export type { AddTaskAttachmentRequest } from './models/AddTaskAttachmentRequest';
export type { AdjustHrLeaveBalanceRequest } from './models/AdjustHrLeaveBalanceRequest';
export type { ApiErrorDetail } from './models/ApiErrorDetail';
export type { ApplyDingTalkMappingRequest } from './models/ApplyDingTalkMappingRequest';
export type { AssignmentCandidatePool } from './models/AssignmentCandidatePool';
export type { AssignmentPolicy } from './models/AssignmentPolicy';
export type { AssignmentPolicyAvailabilityWindow } from './models/AssignmentPolicyAvailabilityWindow';
export { AssignmentPolicyDomain } from './models/AssignmentPolicyDomain';
export { AssignmentPolicyFallbackMode } from './models/AssignmentPolicyFallbackMode';
export { AssignmentPolicyLevel } from './models/AssignmentPolicyLevel';
export type { AssignmentPolicyList } from './models/AssignmentPolicyList';
export type { AssignmentPolicyListResponseEnvelope } from './models/AssignmentPolicyListResponseEnvelope';
export type { AssignmentPolicyResolveContext } from './models/AssignmentPolicyResolveContext';
export type { AssignmentPolicyResolveRequest } from './models/AssignmentPolicyResolveRequest';
export type { AssignmentPolicyResolveResponseEnvelope } from './models/AssignmentPolicyResolveResponseEnvelope';
export type { AssignmentPolicyResolveResult } from './models/AssignmentPolicyResolveResult';
export type { AssignmentPolicyResponseEnvelope } from './models/AssignmentPolicyResponseEnvelope';
export type { AssignmentPolicySourceTrace } from './models/AssignmentPolicySourceTrace';
export type { AssignPlatformTenantAdministratorRequest } from './models/AssignPlatformTenantAdministratorRequest';
export type { AssignTenantMemberDepartmentRequest } from './models/AssignTenantMemberDepartmentRequest';
export type { AuditEvent } from './models/AuditEvent';
export type { AuditEventList } from './models/AuditEventList';
export type { AuditEventListResponseEnvelope } from './models/AuditEventListResponseEnvelope';
export type { AuditEventResponseEnvelope } from './models/AuditEventResponseEnvelope';
export { AuditOutcome } from './models/AuditOutcome';
export { AuthMembership } from './models/AuthMembership';
export type { AuthTenant } from './models/AuthTenant';
export type { AuthUser } from './models/AuthUser';
export type { BossOverview } from './models/BossOverview';
export type { BossOverviewFinance } from './models/BossOverviewFinance';
export type { BossOverviewHr } from './models/BossOverviewHr';
export type { BossOverviewLegal } from './models/BossOverviewLegal';
export type { BossOverviewResponseEnvelope } from './models/BossOverviewResponseEnvelope';
export type { BossOverviewTask } from './models/BossOverviewTask';
export type { CancelHrEmployeeChangeRequest } from './models/CancelHrEmployeeChangeRequest';
export type { CancelHrLeaveRequestRequest } from './models/CancelHrLeaveRequestRequest';
export type { CancelHrOvertimeRequestRequest } from './models/CancelHrOvertimeRequestRequest';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export { ChatContextStrategy } from './models/ChatContextStrategy';
export type { ChatContextUsage } from './models/ChatContextUsage';
export { ChatMode } from './models/ChatMode';
export type { ChatTokenUsage } from './models/ChatTokenUsage';
export type { CompleteProjectRequest } from './models/CompleteProjectRequest';
export { ConnectorContext } from './models/ConnectorContext';
export type { Conversation } from './models/Conversation';
export type { ConversationDetail } from './models/ConversationDetail';
export type { ConversationDetailResponseEnvelope } from './models/ConversationDetailResponseEnvelope';
export type { ConversationListResponseEnvelope } from './models/ConversationListResponseEnvelope';
export type { ConversationListResult } from './models/ConversationListResult';
export type { ConversationMessage } from './models/ConversationMessage';
export { ConversationMessageRole } from './models/ConversationMessageRole';
export type { ConversationResponseEnvelope } from './models/ConversationResponseEnvelope';
export { ConversationVisibility } from './models/ConversationVisibility';
export type { CreateAssignmentPolicyRequest } from './models/CreateAssignmentPolicyRequest';
export type { CreateConversationRequest } from './models/CreateConversationRequest';
export type { CreateDailyWorkReportRequest } from './models/CreateDailyWorkReportRequest';
export type { CreateDepartmentRequest } from './models/CreateDepartmentRequest';
export type { CreateDingTalkIntegrationRequest } from './models/CreateDingTalkIntegrationRequest';
export type { CreateDocumentRequest } from './models/CreateDocumentRequest';
export type { CreateFinanceExpenseCategoryRequest } from './models/CreateFinanceExpenseCategoryRequest';
export type { CreateFinanceExpenseReportRequest } from './models/CreateFinanceExpenseReportRequest';
export type { CreateHrAttendanceRecordRequest } from './models/CreateHrAttendanceRecordRequest';
export type { CreateHrEmployeeChangeRequest } from './models/CreateHrEmployeeChangeRequest';
export type { CreateHrLeaveRequestRequest } from './models/CreateHrLeaveRequestRequest';
export type { CreateHrLeaveTypeRequest } from './models/CreateHrLeaveTypeRequest';
export type { CreateHrOvertimeRequestRequest } from './models/CreateHrOvertimeRequestRequest';
export type { CreateHrProfileRequest } from './models/CreateHrProfileRequest';
export type { CreateKnowledgeBaseMemberRequest } from './models/CreateKnowledgeBaseMemberRequest';
export type { CreateKnowledgeBaseRequest } from './models/CreateKnowledgeBaseRequest';
export { CreateKnowledgeDocumentRequest } from './models/CreateKnowledgeDocumentRequest';
export type { CreateKnowledgeDocumentVersionRequest } from './models/CreateKnowledgeDocumentVersionRequest';
export type { CreateLegalContractRequest } from './models/CreateLegalContractRequest';
export type { CreateMeetingRequest } from './models/CreateMeetingRequest';
export type { CreatePlatformTenantRequest } from './models/CreatePlatformTenantRequest';
export type { CreateProjectRequest } from './models/CreateProjectRequest';
export type { CreateResourceAclRequest } from './models/CreateResourceAclRequest';
export type { CreateRoleRequest } from './models/CreateRoleRequest';
export type { CreateTaskCommentRequest } from './models/CreateTaskCommentRequest';
export type { CreateTaskRequest } from './models/CreateTaskRequest';
export type { CreateTenantInvitationRequest } from './models/CreateTenantInvitationRequest';
export type { CreateTurnRequest } from './models/CreateTurnRequest';
export type { CreateUploadSessionRequest } from './models/CreateUploadSessionRequest';
export type { CreateWeeklyWorkReportRequest } from './models/CreateWeeklyWorkReportRequest';
export type { DashboardMeetingMetrics } from './models/DashboardMeetingMetrics';
export type { DashboardMeetingTodo } from './models/DashboardMeetingTodo';
export type { DashboardNotificationMetrics } from './models/DashboardNotificationMetrics';
export type { DashboardOverview } from './models/DashboardOverview';
export type { DashboardOverviewResponseEnvelope } from './models/DashboardOverviewResponseEnvelope';
export type { DashboardProjectMetrics } from './models/DashboardProjectMetrics';
export type { DashboardReportMetrics } from './models/DashboardReportMetrics';
export type { DashboardReportTodo } from './models/DashboardReportTodo';
export type { DashboardTaskMetrics } from './models/DashboardTaskMetrics';
export type { DashboardTaskStatistics } from './models/DashboardTaskStatistics';
export type { DashboardTaskStatisticsResponseEnvelope } from './models/DashboardTaskStatisticsResponseEnvelope';
export type { DashboardTaskTodo } from './models/DashboardTaskTodo';
export type { DashboardTodoList } from './models/DashboardTodoList';
export type { DashboardTodoListResponseEnvelope } from './models/DashboardTodoListResponseEnvelope';
export type { DashboardUpcomingMeeting } from './models/DashboardUpcomingMeeting';
export type { DashboardUpcomingMeetingList } from './models/DashboardUpcomingMeetingList';
export type { DashboardUpcomingMeetingListResponseEnvelope } from './models/DashboardUpcomingMeetingListResponseEnvelope';
export { DataScope } from './models/DataScope';
export type { DepartmentResponseEnvelope } from './models/DepartmentResponseEnvelope';
export { DepartmentStatus } from './models/DepartmentStatus';
export type { DepartmentSummary } from './models/DepartmentSummary';
export type { DepartmentTree } from './models/DepartmentTree';
export type { DepartmentTreeNode } from './models/DepartmentTreeNode';
export type { DepartmentTreeResponseEnvelope } from './models/DepartmentTreeResponseEnvelope';
export type { DingTalkConnectorPlannedCall } from './models/DingTalkConnectorPlannedCall';
export type { DingTalkConnectorPlanRequest } from './models/DingTalkConnectorPlanRequest';
export type { DingTalkConnectorPlanResponseEnvelope } from './models/DingTalkConnectorPlanResponseEnvelope';
export type { DingTalkConnectorPlanResult } from './models/DingTalkConnectorPlanResult';
export type { DingTalkConnectorTool } from './models/DingTalkConnectorTool';
export type { DingTalkDepartment } from './models/DingTalkDepartment';
export type { DingTalkDepartmentList } from './models/DingTalkDepartmentList';
export type { DingTalkDepartmentListResponseEnvelope } from './models/DingTalkDepartmentListResponseEnvelope';
export { DingTalkDepartmentMappingPreview } from './models/DingTalkDepartmentMappingPreview';
export { DingTalkDepartmentMappingResolution } from './models/DingTalkDepartmentMappingResolution';
export type { DingTalkIntegration } from './models/DingTalkIntegration';
export { DingTalkIntegrationMode } from './models/DingTalkIntegrationMode';
export type { DingTalkIntegrationResponseEnvelope } from './models/DingTalkIntegrationResponseEnvelope';
export { DingTalkIntegrationStatus } from './models/DingTalkIntegrationStatus';
export type { DingTalkMappingCredential } from './models/DingTalkMappingCredential';
export type { DingTalkMappingPreview } from './models/DingTalkMappingPreview';
export type { DingTalkMappingPreviewResponseEnvelope } from './models/DingTalkMappingPreviewResponseEnvelope';
export type { DingTalkMappingResponseEnvelope } from './models/DingTalkMappingResponseEnvelope';
export type { DingTalkMappingResult } from './models/DingTalkMappingResult';
export type { DingTalkMappingSummary } from './models/DingTalkMappingSummary';
export type { DingTalkRoleAssignment } from './models/DingTalkRoleAssignment';
export type { DingTalkSyncJob } from './models/DingTalkSyncJob';
export type { DingTalkSyncJobList } from './models/DingTalkSyncJobList';
export type { DingTalkSyncJobListResponseEnvelope } from './models/DingTalkSyncJobListResponseEnvelope';
export type { DingTalkSyncJobResponseEnvelope } from './models/DingTalkSyncJobResponseEnvelope';
export { DingTalkSyncJobStatus } from './models/DingTalkSyncJobStatus';
export { DingTalkSyncScope } from './models/DingTalkSyncScope';
export { DingTalkSyncSource } from './models/DingTalkSyncSource';
export { DingTalkSyncType } from './models/DingTalkSyncType';
export type { DingTalkUser } from './models/DingTalkUser';
export type { DingTalkUserList } from './models/DingTalkUserList';
export type { DingTalkUserListResponseEnvelope } from './models/DingTalkUserListResponseEnvelope';
export { DingTalkUserMappingPreview } from './models/DingTalkUserMappingPreview';
export { DingTalkUserMappingResolution } from './models/DingTalkUserMappingResolution';
export type { DingTalkVisibleDepartmentSnapshot } from './models/DingTalkVisibleDepartmentSnapshot';
export type { DingTalkVisibleUserSnapshot } from './models/DingTalkVisibleUserSnapshot';
export type { DocumentDetail } from './models/DocumentDetail';
export type { DocumentList } from './models/DocumentList';
export type { DocumentListResponseEnvelope } from './models/DocumentListResponseEnvelope';
export type { DocumentResponseEnvelope } from './models/DocumentResponseEnvelope';
export type { DocumentSummary } from './models/DocumentSummary';
export { DocumentVisibility } from './models/DocumentVisibility';
export type { ErrorResponseEnvelope } from './models/ErrorResponseEnvelope';
export type { FileMetadata } from './models/FileMetadata';
export type { FileMetadataResponseEnvelope } from './models/FileMetadataResponseEnvelope';
export { FileUploadPurpose } from './models/FileUploadPurpose';
export type { FinanceExpenseActionRequest } from './models/FinanceExpenseActionRequest';
export type { FinanceExpenseAttachment } from './models/FinanceExpenseAttachment';
export type { FinanceExpenseCategory } from './models/FinanceExpenseCategory';
export type { FinanceExpenseCategoryList } from './models/FinanceExpenseCategoryList';
export type { FinanceExpenseCategoryListResponseEnvelope } from './models/FinanceExpenseCategoryListResponseEnvelope';
export type { FinanceExpenseCategoryResponseEnvelope } from './models/FinanceExpenseCategoryResponseEnvelope';
export type { FinanceExpenseItem } from './models/FinanceExpenseItem';
export type { FinanceExpenseItemInput } from './models/FinanceExpenseItemInput';
export type { FinanceExpenseReport } from './models/FinanceExpenseReport';
export type { FinanceExpenseReportList } from './models/FinanceExpenseReportList';
export type { FinanceExpenseReportListResponseEnvelope } from './models/FinanceExpenseReportListResponseEnvelope';
export type { FinanceExpenseReportResponseEnvelope } from './models/FinanceExpenseReportResponseEnvelope';
export { FinanceExpenseStatus } from './models/FinanceExpenseStatus';
export type { FinanceExpenseStatusHistory } from './models/FinanceExpenseStatusHistory';
export type { FinanceExpenseSummary } from './models/FinanceExpenseSummary';
export type { FinanceExpenseSummaryResponseEnvelope } from './models/FinanceExpenseSummaryResponseEnvelope';
export type { FinanceExpenseVersionRequest } from './models/FinanceExpenseVersionRequest';
export { FinancePaymentMethod } from './models/FinancePaymentMethod';
export type { FinanceProjectSpend } from './models/FinanceProjectSpend';
export type { FinanceProjectSpendResponseEnvelope } from './models/FinanceProjectSpendResponseEnvelope';
export type { HrAttendanceImportResult } from './models/HrAttendanceImportResult';
export type { HrAttendanceImportResultResponseEnvelope } from './models/HrAttendanceImportResultResponseEnvelope';
export { HrAttendanceRecord } from './models/HrAttendanceRecord';
export type { HrAttendanceRecordList } from './models/HrAttendanceRecordList';
export type { HrAttendanceRecordListResponseEnvelope } from './models/HrAttendanceRecordListResponseEnvelope';
export type { HrAttendanceRecordResponseEnvelope } from './models/HrAttendanceRecordResponseEnvelope';
export { HrAttendanceStatus } from './models/HrAttendanceStatus';
export type { HrAttendanceSummaryReport } from './models/HrAttendanceSummaryReport';
export type { HrAttendanceSummaryReportResponseEnvelope } from './models/HrAttendanceSummaryReportResponseEnvelope';
export type { HrEmployeeChange } from './models/HrEmployeeChange';
export type { HrEmployeeChangeList } from './models/HrEmployeeChangeList';
export type { HrEmployeeChangeListResponseEnvelope } from './models/HrEmployeeChangeListResponseEnvelope';
export type { HrEmployeeChangeResponseEnvelope } from './models/HrEmployeeChangeResponseEnvelope';
export { HrEmployeeChangeStatus } from './models/HrEmployeeChangeStatus';
export { HrEmployeeChangeType } from './models/HrEmployeeChangeType';
export type { HrHeadcountReport } from './models/HrHeadcountReport';
export type { HrHeadcountReportResponseEnvelope } from './models/HrHeadcountReportResponseEnvelope';
export type { HrLeaveBalance } from './models/HrLeaveBalance';
export type { HrLeaveBalanceList } from './models/HrLeaveBalanceList';
export type { HrLeaveBalanceListResponseEnvelope } from './models/HrLeaveBalanceListResponseEnvelope';
export type { HrLeaveBalanceResponseEnvelope } from './models/HrLeaveBalanceResponseEnvelope';
export type { HrLeaveRequest } from './models/HrLeaveRequest';
export type { HrLeaveRequestList } from './models/HrLeaveRequestList';
export type { HrLeaveRequestListResponseEnvelope } from './models/HrLeaveRequestListResponseEnvelope';
export type { HrLeaveRequestResponseEnvelope } from './models/HrLeaveRequestResponseEnvelope';
export { HrLeaveRequestStatus } from './models/HrLeaveRequestStatus';
export type { HrLeaveSummaryReport } from './models/HrLeaveSummaryReport';
export type { HrLeaveSummaryReportResponseEnvelope } from './models/HrLeaveSummaryReportResponseEnvelope';
export type { HrLeaveType } from './models/HrLeaveType';
export type { HrLeaveTypeList } from './models/HrLeaveTypeList';
export type { HrLeaveTypeListResponseEnvelope } from './models/HrLeaveTypeListResponseEnvelope';
export type { HrLeaveTypeResponseEnvelope } from './models/HrLeaveTypeResponseEnvelope';
export { HrLeaveUnit } from './models/HrLeaveUnit';
export type { HrLeaveYearAllocation } from './models/HrLeaveYearAllocation';
export type { HrOvertimeRequest } from './models/HrOvertimeRequest';
export type { HrOvertimeRequestList } from './models/HrOvertimeRequestList';
export type { HrOvertimeRequestListResponseEnvelope } from './models/HrOvertimeRequestListResponseEnvelope';
export type { HrOvertimeRequestResponseEnvelope } from './models/HrOvertimeRequestResponseEnvelope';
export { HrOvertimeRequestStatus } from './models/HrOvertimeRequestStatus';
export type { HrOvertimeSummaryReport } from './models/HrOvertimeSummaryReport';
export type { HrOvertimeSummaryReportResponseEnvelope } from './models/HrOvertimeSummaryReportResponseEnvelope';
export type { HrProfile } from './models/HrProfile';
export type { HrProfileList } from './models/HrProfileList';
export type { HrProfileListResponseEnvelope } from './models/HrProfileListResponseEnvelope';
export type { HrProfileResponseEnvelope } from './models/HrProfileResponseEnvelope';
export { HrProfileStatus } from './models/HrProfileStatus';
export type { ImageResponseEnvelope } from './models/ImageResponseEnvelope';
export { ImageResult } from './models/ImageResult';
export type { ImportDingTalkVisibleOrganizationSnapshotRequest } from './models/ImportDingTalkVisibleOrganizationSnapshotRequest';
export type { ImportHrAttendanceRecordsRequest } from './models/ImportHrAttendanceRecordsRequest';
export type { InitialTenantAdministratorRequest } from './models/InitialTenantAdministratorRequest';
export type { KnowledgeBase } from './models/KnowledgeBase';
export type { KnowledgeBaseList } from './models/KnowledgeBaseList';
export type { KnowledgeBaseListResponseEnvelope } from './models/KnowledgeBaseListResponseEnvelope';
export type { KnowledgeBaseMember } from './models/KnowledgeBaseMember';
export type { KnowledgeBaseMemberList } from './models/KnowledgeBaseMemberList';
export type { KnowledgeBaseMemberListResponseEnvelope } from './models/KnowledgeBaseMemberListResponseEnvelope';
export { KnowledgeBaseMemberPermission } from './models/KnowledgeBaseMemberPermission';
export type { KnowledgeBaseMemberResponseEnvelope } from './models/KnowledgeBaseMemberResponseEnvelope';
export type { KnowledgeBaseResponseEnvelope } from './models/KnowledgeBaseResponseEnvelope';
export { KnowledgeBaseVisibilityScope } from './models/KnowledgeBaseVisibilityScope';
export type { KnowledgeDocument } from './models/KnowledgeDocument';
export type { KnowledgeDocumentList } from './models/KnowledgeDocumentList';
export type { KnowledgeDocumentListResponseEnvelope } from './models/KnowledgeDocumentListResponseEnvelope';
export type { KnowledgeDocumentResponseEnvelope } from './models/KnowledgeDocumentResponseEnvelope';
export { KnowledgeDocumentStatus } from './models/KnowledgeDocumentStatus';
export { KnowledgeDocumentVisibilityScope } from './models/KnowledgeDocumentVisibilityScope';
export type { KnowledgeQueryCitation } from './models/KnowledgeQueryCitation';
export type { KnowledgeQueryRequest } from './models/KnowledgeQueryRequest';
export type { KnowledgeQueryResponse } from './models/KnowledgeQueryResponse';
export type { KnowledgeQueryResponseEnvelope } from './models/KnowledgeQueryResponseEnvelope';
export type { KnowledgeToolCitation } from './models/KnowledgeToolCitation';
export type { LegalContract } from './models/LegalContract';
export type { LegalContractActionRequest } from './models/LegalContractActionRequest';
export type { LegalContractAmountSummary } from './models/LegalContractAmountSummary';
export type { LegalContractAttachment } from './models/LegalContractAttachment';
export type { LegalContractList } from './models/LegalContractList';
export type { LegalContractListResponseEnvelope } from './models/LegalContractListResponseEnvelope';
export type { LegalContractResponseEnvelope } from './models/LegalContractResponseEnvelope';
export { LegalContractStatus } from './models/LegalContractStatus';
export type { LegalContractStatusHistory } from './models/LegalContractStatusHistory';
export type { LegalContractSummary } from './models/LegalContractSummary';
export type { LegalContractSummaryResponseEnvelope } from './models/LegalContractSummaryResponseEnvelope';
export { LegalContractType } from './models/LegalContractType';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { LoginResponseEnvelope } from './models/LoginResponseEnvelope';
export type { MarkFinanceExpenseReportPaidRequest } from './models/MarkFinanceExpenseReportPaidRequest';
export type { Meeting } from './models/Meeting';
export type { MeetingAgendaItem } from './models/MeetingAgendaItem';
export { MeetingAttendanceStatus } from './models/MeetingAttendanceStatus';
export type { MeetingList } from './models/MeetingList';
export type { MeetingListResponseEnvelope } from './models/MeetingListResponseEnvelope';
export type { MeetingMemberIdentity } from './models/MeetingMemberIdentity';
export type { MeetingMinutes } from './models/MeetingMinutes';
export type { MeetingMinutesActionItem } from './models/MeetingMinutesActionItem';
export type { MeetingMinutesContent } from './models/MeetingMinutesContent';
export type { MeetingMinutesResponseEnvelope } from './models/MeetingMinutesResponseEnvelope';
export { MeetingMinutesStatus } from './models/MeetingMinutesStatus';
export type { MeetingMinutesVersionRequest } from './models/MeetingMinutesVersionRequest';
export type { MeetingParticipant } from './models/MeetingParticipant';
export type { MeetingParticipantList } from './models/MeetingParticipantList';
export type { MeetingParticipantListResponseEnvelope } from './models/MeetingParticipantListResponseEnvelope';
export type { MeetingParticipantResponseEnvelope } from './models/MeetingParticipantResponseEnvelope';
export { MeetingParticipantRole } from './models/MeetingParticipantRole';
export type { MeetingResponseEnvelope } from './models/MeetingResponseEnvelope';
export { MeetingResponseStatus } from './models/MeetingResponseStatus';
export { MeetingStatus } from './models/MeetingStatus';
export type { MeetingTransitionRequest } from './models/MeetingTransitionRequest';
export { MeetingTransitionTarget } from './models/MeetingTransitionTarget';
export { MemberStatus } from './models/MemberStatus';
export type { MeResponse } from './models/MeResponse';
export type { MeResponseEnvelope } from './models/MeResponseEnvelope';
export type { NotificationList } from './models/NotificationList';
export type { NotificationListResponseEnvelope } from './models/NotificationListResponseEnvelope';
export type { NotificationMarkAllRead } from './models/NotificationMarkAllRead';
export type { NotificationMarkAllReadResponseEnvelope } from './models/NotificationMarkAllReadResponseEnvelope';
export type { NotificationResponseEnvelope } from './models/NotificationResponseEnvelope';
export type { NotificationResult } from './models/NotificationResult';
export type { NotificationUnreadCount } from './models/NotificationUnreadCount';
export type { NotificationUnreadCountResponseEnvelope } from './models/NotificationUnreadCountResponseEnvelope';
export type { NullableMeetingMinutesResponseEnvelope } from './models/NullableMeetingMinutesResponseEnvelope';
export { OrganizationImportDepartmentAction } from './models/OrganizationImportDepartmentAction';
export type { OrganizationImportDepartmentInput } from './models/OrganizationImportDepartmentInput';
export type { OrganizationImportDepartmentPreview } from './models/OrganizationImportDepartmentPreview';
export type { OrganizationImportDepartmentResult } from './models/OrganizationImportDepartmentResult';
export type { OrganizationImportIssue } from './models/OrganizationImportIssue';
export { OrganizationImportIssueScope } from './models/OrganizationImportIssueScope';
export type { OrganizationImportMemberCredential } from './models/OrganizationImportMemberCredential';
export type { OrganizationImportMemberInput } from './models/OrganizationImportMemberInput';
export type { OrganizationImportMemberPreview } from './models/OrganizationImportMemberPreview';
export type { OrganizationImportRequest } from './models/OrganizationImportRequest';
export type { OrganizationImportResult } from './models/OrganizationImportResult';
export type { OrganizationImportResultResponseEnvelope } from './models/OrganizationImportResultResponseEnvelope';
export type { OrganizationImportSummary } from './models/OrganizationImportSummary';
export type { OrganizationImportValidation } from './models/OrganizationImportValidation';
export type { OrganizationImportValidationResponseEnvelope } from './models/OrganizationImportValidationResponseEnvelope';
export type { Permission } from './models/Permission';
export type { PermissionList } from './models/PermissionList';
export type { PermissionListResponseEnvelope } from './models/PermissionListResponseEnvelope';
export type { PlatformAdministratorIdentity } from './models/PlatformAdministratorIdentity';
export type { PlatformAuditEvent } from './models/PlatformAuditEvent';
export type { PlatformAuditEventList } from './models/PlatformAuditEventList';
export type { PlatformAuditEventListResponseEnvelope } from './models/PlatformAuditEventListResponseEnvelope';
export type { PlatformAuditEventResponseEnvelope } from './models/PlatformAuditEventResponseEnvelope';
export type { PlatformLoginRequest } from './models/PlatformLoginRequest';
export type { PlatformLoginResponse } from './models/PlatformLoginResponse';
export type { PlatformLoginResponseEnvelope } from './models/PlatformLoginResponseEnvelope';
export type { PlatformMeResponse } from './models/PlatformMeResponse';
export type { PlatformMeResponseEnvelope } from './models/PlatformMeResponseEnvelope';
export { PlatformRole } from './models/PlatformRole';
export type { PlatformTenantAdministrator } from './models/PlatformTenantAdministrator';
export type { PlatformTenantAdministratorAssignment } from './models/PlatformTenantAdministratorAssignment';
export type { PlatformTenantAdministratorAssignmentResponseEnvelope } from './models/PlatformTenantAdministratorAssignmentResponseEnvelope';
export type { PlatformTenantAdministratorList } from './models/PlatformTenantAdministratorList';
export type { PlatformTenantAdministratorListResponseEnvelope } from './models/PlatformTenantAdministratorListResponseEnvelope';
export type { PlatformTenantDetail } from './models/PlatformTenantDetail';
export type { PlatformTenantList } from './models/PlatformTenantList';
export type { PlatformTenantListResponseEnvelope } from './models/PlatformTenantListResponseEnvelope';
export type { PlatformTenantProvisioningResponse } from './models/PlatformTenantProvisioningResponse';
export type { PlatformTenantProvisioningResponseEnvelope } from './models/PlatformTenantProvisioningResponseEnvelope';
export type { PlatformTenantResponseEnvelope } from './models/PlatformTenantResponseEnvelope';
export type { PreviewDingTalkMappingRequest } from './models/PreviewDingTalkMappingRequest';
export type { ProjectCode } from './models/ProjectCode';
export type { ProjectList } from './models/ProjectList';
export type { ProjectListResponseEnvelope } from './models/ProjectListResponseEnvelope';
export type { ProjectMemberList } from './models/ProjectMemberList';
export type { ProjectMemberListResponseEnvelope } from './models/ProjectMemberListResponseEnvelope';
export type { ProjectMemberResponseEnvelope } from './models/ProjectMemberResponseEnvelope';
export { ProjectMemberRole } from './models/ProjectMemberRole';
export type { ProjectMemberSummary } from './models/ProjectMemberSummary';
export type { ProjectReasonRequest } from './models/ProjectReasonRequest';
export type { ProjectResponseEnvelope } from './models/ProjectResponseEnvelope';
export { ProjectStatus } from './models/ProjectStatus';
export type { ProjectSummary } from './models/ProjectSummary';
export type { ProjectVersionRequest } from './models/ProjectVersionRequest';
export type { RefreshTokenRequest } from './models/RefreshTokenRequest';
export type { RenewLegalContractRequest } from './models/RenewLegalContractRequest';
export type { ReplaceRolePermissionsRequest } from './models/ReplaceRolePermissionsRequest';
export type { ReplaceTaskAssigneesRequest } from './models/ReplaceTaskAssigneesRequest';
export type { ReplaceTenantMemberRolesRequest } from './models/ReplaceTenantMemberRolesRequest';
export type { ResourceAclEntry } from './models/ResourceAclEntry';
export type { ResourceAclList } from './models/ResourceAclList';
export type { ResourceAclListResponseEnvelope } from './models/ResourceAclListResponseEnvelope';
export type { ResourceAclResponseEnvelope } from './models/ResourceAclResponseEnvelope';
export { RespondMeetingParticipantRequest } from './models/RespondMeetingParticipantRequest';
export { ReviewFinanceExpenseReportRequest } from './models/ReviewFinanceExpenseReportRequest';
export { ReviewHrAttendanceRecordRequest } from './models/ReviewHrAttendanceRecordRequest';
export { ReviewHrEmployeeChangeRequest } from './models/ReviewHrEmployeeChangeRequest';
export { ReviewHrLeaveRequestRequest } from './models/ReviewHrLeaveRequestRequest';
export { ReviewHrOvertimeRequestRequest } from './models/ReviewHrOvertimeRequestRequest';
export type { ReviewWorkReportRequest } from './models/ReviewWorkReportRequest';
export type { Role } from './models/Role';
export type { RoleList } from './models/RoleList';
export type { RoleListResponseEnvelope } from './models/RoleListResponseEnvelope';
export type { RoleResponseEnvelope } from './models/RoleResponseEnvelope';
export type { SuspendPlatformTenantRequest } from './models/SuspendPlatformTenantRequest';
export type { TaskActivity } from './models/TaskActivity';
export type { TaskActivityList } from './models/TaskActivityList';
export type { TaskActivityListResponseEnvelope } from './models/TaskActivityListResponseEnvelope';
export type { TaskAssignee } from './models/TaskAssignee';
export { TaskAssigneeType } from './models/TaskAssigneeType';
export type { TaskAttachment } from './models/TaskAttachment';
export type { TaskAttachmentList } from './models/TaskAttachmentList';
export type { TaskAttachmentListResponseEnvelope } from './models/TaskAttachmentListResponseEnvelope';
export type { TaskAttachmentResponseEnvelope } from './models/TaskAttachmentResponseEnvelope';
export type { TaskComment } from './models/TaskComment';
export type { TaskCommentList } from './models/TaskCommentList';
export type { TaskCommentListResponseEnvelope } from './models/TaskCommentListResponseEnvelope';
export type { TaskCommentResponseEnvelope } from './models/TaskCommentResponseEnvelope';
export type { TaskList } from './models/TaskList';
export type { TaskListResponseEnvelope } from './models/TaskListResponseEnvelope';
export type { TaskMemberIdentity } from './models/TaskMemberIdentity';
export { TaskPriority } from './models/TaskPriority';
export type { TaskResponseEnvelope } from './models/TaskResponseEnvelope';
export { TaskStatus } from './models/TaskStatus';
export type { TaskSummary } from './models/TaskSummary';
export type { TaskTransitionRequest } from './models/TaskTransitionRequest';
export { TaskTransitionTarget } from './models/TaskTransitionTarget';
export { TenantAdministratorAssignmentStatus } from './models/TenantAdministratorAssignmentStatus';
export type { TenantDetail } from './models/TenantDetail';
export type { TenantInvitation } from './models/TenantInvitation';
export type { TenantInvitationAcceptance } from './models/TenantInvitationAcceptance';
export type { TenantInvitationAcceptanceResponseEnvelope } from './models/TenantInvitationAcceptanceResponseEnvelope';
export type { TenantInvitationCreated } from './models/TenantInvitationCreated';
export type { TenantInvitationCreatedResponseEnvelope } from './models/TenantInvitationCreatedResponseEnvelope';
export type { TenantInvitationList } from './models/TenantInvitationList';
export type { TenantInvitationListResponseEnvelope } from './models/TenantInvitationListResponseEnvelope';
export { TenantInvitationStatus } from './models/TenantInvitationStatus';
export type { TenantMember } from './models/TenantMember';
export type { TenantMemberList } from './models/TenantMemberList';
export type { TenantMemberListResponseEnvelope } from './models/TenantMemberListResponseEnvelope';
export type { TenantMemberResponseEnvelope } from './models/TenantMemberResponseEnvelope';
export type { TenantMemberRole } from './models/TenantMemberRole';
export type { TenantResponseEnvelope } from './models/TenantResponseEnvelope';
export type { TenantSearchPolicy } from './models/TenantSearchPolicy';
export type { TenantSearchPolicyResponseEnvelope } from './models/TenantSearchPolicyResponseEnvelope';
export { TenantStatus } from './models/TenantStatus';
export type { TerminateLegalContractRequest } from './models/TerminateLegalContractRequest';
export type { TokenPairResponse } from './models/TokenPairResponse';
export type { TokenPairResponseEnvelope } from './models/TokenPairResponseEnvelope';
export { ToolResultResourceReference } from './models/ToolResultResourceReference';
export type { ToolSource } from './models/ToolSource';
export type { TransferProjectOwnerRequest } from './models/TransferProjectOwnerRequest';
export type { Turn } from './models/Turn';
export type { TurnCapabilities } from './models/TurnCapabilities';
export type { TurnErrorDetail } from './models/TurnErrorDetail';
export { TurnPhase } from './models/TurnPhase';
export type { TurnResponseEnvelope } from './models/TurnResponseEnvelope';
export { TurnStatus } from './models/TurnStatus';
export type { TurnStreamCompletedEvent } from './models/TurnStreamCompletedEvent';
export type { TurnStreamContentDeltaEvent } from './models/TurnStreamContentDeltaEvent';
export type { TurnStreamErrorEvent } from './models/TurnStreamErrorEvent';
export type { TurnStreamEvent } from './models/TurnStreamEvent';
export type { TurnStreamRelatedQuestionsEvent } from './models/TurnStreamRelatedQuestionsEvent';
export type { TurnStreamStartedEvent } from './models/TurnStreamStartedEvent';
export type { TurnStreamStatusEvent } from './models/TurnStreamStatusEvent';
export type { TurnStreamToolCallEvent } from './models/TurnStreamToolCallEvent';
export { TurnStreamToolResultEvent } from './models/TurnStreamToolResultEvent';
export type { TurnStreamUsageEvent } from './models/TurnStreamUsageEvent';
export type { UpdateAssignmentPolicyRequest } from './models/UpdateAssignmentPolicyRequest';
export type { UpdateConversationRequest } from './models/UpdateConversationRequest';
export type { UpdateDepartmentRequest } from './models/UpdateDepartmentRequest';
export type { UpdateDingTalkIntegrationRequest } from './models/UpdateDingTalkIntegrationRequest';
export type { UpdateDocumentRequest } from './models/UpdateDocumentRequest';
export type { UpdateFinanceExpenseCategoryRequest } from './models/UpdateFinanceExpenseCategoryRequest';
export type { UpdateFinanceExpenseReportRequest } from './models/UpdateFinanceExpenseReportRequest';
export type { UpdateHrAttendanceRecordRequest } from './models/UpdateHrAttendanceRecordRequest';
export type { UpdateHrLeaveTypeRequest } from './models/UpdateHrLeaveTypeRequest';
export type { UpdateHrProfileRequest } from './models/UpdateHrProfileRequest';
export type { UpdateKnowledgeBaseMemberRequest } from './models/UpdateKnowledgeBaseMemberRequest';
export type { UpdateKnowledgeBaseRequest } from './models/UpdateKnowledgeBaseRequest';
export type { UpdateLegalContractRequest } from './models/UpdateLegalContractRequest';
export type { UpdateMeetingParticipantRequest } from './models/UpdateMeetingParticipantRequest';
export type { UpdateMeetingRequest } from './models/UpdateMeetingRequest';
export type { UpdatePlatformTenantRequest } from './models/UpdatePlatformTenantRequest';
export { UpdateProjectMemberRequest } from './models/UpdateProjectMemberRequest';
export type { UpdateProjectRequest } from './models/UpdateProjectRequest';
export type { UpdateRoleRequest } from './models/UpdateRoleRequest';
export type { UpdateTaskCommentRequest } from './models/UpdateTaskCommentRequest';
export type { UpdateTaskRequest } from './models/UpdateTaskRequest';
export type { UpdateTenantMemberAccountRequest } from './models/UpdateTenantMemberAccountRequest';
export { UpdateTenantMemberRequest } from './models/UpdateTenantMemberRequest';
export type { UpdateTenantRequest } from './models/UpdateTenantRequest';
export type { UpdateTenantSearchPolicyRequest } from './models/UpdateTenantSearchPolicyRequest';
export type { UpdateUserProfileRequest } from './models/UpdateUserProfileRequest';
export type { UpdateWorkReportRequest } from './models/UpdateWorkReportRequest';
export type { UploadInstruction } from './models/UploadInstruction';
export { UploadMode } from './models/UploadMode';
export type { UploadSession } from './models/UploadSession';
export type { UploadSessionResponseEnvelope } from './models/UploadSessionResponseEnvelope';
export { UploadSessionStatus } from './models/UploadSessionStatus';
export type { UpsertMeetingMinutesRequest } from './models/UpsertMeetingMinutesRequest';
export type { UserProfile } from './models/UserProfile';
export type { UserProfileDepartment } from './models/UserProfileDepartment';
export type { UserProfileResponseEnvelope } from './models/UserProfileResponseEnvelope';
export type { VersionRequest } from './models/VersionRequest';
export type { WithdrawHrLeaveRequestRequest } from './models/WithdrawHrLeaveRequestRequest';
export type { WorkReport } from './models/WorkReport';
export type { WorkReportContent } from './models/WorkReportContent';
export type { WorkReportList } from './models/WorkReportList';
export type { WorkReportListResponseEnvelope } from './models/WorkReportListResponseEnvelope';
export type { WorkReportMemberIdentity } from './models/WorkReportMemberIdentity';
export type { WorkReportResponseEnvelope } from './models/WorkReportResponseEnvelope';
export { WorkReportReviewDecision } from './models/WorkReportReviewDecision';
export type { WorkReportStatistics } from './models/WorkReportStatistics';
export type { WorkReportStatisticsResponseEnvelope } from './models/WorkReportStatisticsResponseEnvelope';
export { WorkReportStatus } from './models/WorkReportStatus';
export { WorkReportType } from './models/WorkReportType';
export type { WorkReportVersionRequest } from './models/WorkReportVersionRequest';

export { AclService } from './services/AclService';
export { AssignmentService } from './services/AssignmentService';
export { AuditService } from './services/AuditService';
export { AuthService } from './services/AuthService';
export { BossOverviewService } from './services/BossOverviewService';
export { ConversationService } from './services/ConversationService';
export { DashboardService } from './services/DashboardService';
export { DefaultService } from './services/DefaultService';
export { DingTalkService } from './services/DingTalkService';
export { DocumentService } from './services/DocumentService';
export { FileService } from './services/FileService';
export { FinanceService } from './services/FinanceService';
export { HrService } from './services/HrService';
export { ImageService } from './services/ImageService';
export { KnowledgeBaseService } from './services/KnowledgeBaseService';
export { LegalService } from './services/LegalService';
export { MeetingService } from './services/MeetingService';
export { NotificationService } from './services/NotificationService';
export { OrganizationService } from './services/OrganizationService';
export { PlatformAuditService } from './services/PlatformAuditService';
export { PlatformAuthService } from './services/PlatformAuthService';
export { PlatformTenantService } from './services/PlatformTenantService';
export { ProjectService } from './services/ProjectService';
export { RbacService } from './services/RbacService';
export { TaskService } from './services/TaskService';
export { TenantService } from './services/TenantService';
export { UserService } from './services/UserService';
export { WorkReportService } from './services/WorkReportService';
