export const TENANT_PERMISSION_DEFINITIONS = [
    ['tenant.read', '查看当前租户'],
    ['tenant.update', '修改当前租户'],
    ['member.read', '查看租户成员'],
    ['member.invite', '邀请租户成员'],
    ['member.update', '修改租户成员'],
    ['member.account.update', '修改租户成员账号'],
    ['member.credential.reset', '重置租户成员凭证'],
    ['member.remove', '移除租户成员'],
    ['department.read', '查看租户部门'],
    ['department.create', '创建租户部门'],
    ['department.update', '修改租户部门'],
    ['department.delete', '删除租户部门'],
    ['department.member.assign', '调整成员所属部门'],
    ['project.create', '创建租户项目'],
    ['project.read', '查看参与的项目'],
    ['project.update', '修改参与的项目'],
    ['project.delete', '删除无业务数据的项目'],
    ['project.member.read', '查看项目成员'],
    ['project.member.manage', '管理项目成员'],
    ['project.complete', '完成项目'],
    ['project.reopen', '重新开启已完成项目'],
    ['project.archive', '归档和恢复项目'],
    ['project.manage_all', '管理当前租户全部项目'],
    ['task.create', '创建项目任务'],
    ['task.read', '查看项目任务'],
    ['task.update', '修改项目任务'],
    ['task.delete', '删除项目任务'],
    ['task.status.update', '变更任务状态'],
    ['task.assignee.manage', '管理任务负责人和协作人'],
    ['task.comment.create', '新增任务评论'],
    ['task.comment.update', '修改任务评论'],
    ['task.comment.delete', '删除任务评论'],
    ['task.attachment.manage', '管理任务附件'],
    ['meeting.create', '创建会议'],
    ['meeting.read', '查看参与的会议'],
    ['meeting.update', '修改会议资料'],
    ['meeting.delete', '删除会议草稿'],
    ['meeting.status.update', '变更会议状态'],
    ['meeting.participant.manage', '管理会议参会人'],
    ['meeting.minutes.manage', '管理会议纪要'],
    ['meeting.manage_all', '管理当前租户全部会议'],
    ['role.read', '查看权限和角色'],
    ['role.create', '创建租户角色'],
    ['role.update', '修改角色及权限'],
    ['role.delete', '删除租户角色'],
    ['role.assign', '为成员分配角色'],
    ['document.create', '创建文档'],
    ['document.read', '读取授权范围内文档'],
    ['document.update', '修改授权范围内文档'],
    ['document.delete', '删除授权范围内文档'],
    ['document.share', '管理文档资源级授权'],
    ['document.manage_all', '管理当前租户全部文档'],
    ['knowledge_base.create', '创建知识库'],
    ['knowledge_base.read', '查看可访问的知识库'],
    ['knowledge_base.update', '修改可访问的知识库'],
    ['knowledge_base.delete', '删除可访问的知识库'],
    ['knowledge_base.member.manage', '管理知识库成员'],
    ['knowledge_base.document.manage', '管理知识库文档'],
    ['knowledge_base.query', '查询知识库内容'],
    ['knowledge_base.manage_all', '管理当前租户全部知识库'],
    ['audit.read', '查询当前租户审计事件'],
    ['work_report.create', '\u521b\u5efa\u65e5\u62a5\u5468\u62a5'],
    ['work_report.read', '\u67e5\u770b\u53ef\u89c1\u65e5\u62a5\u5468\u62a5'],
    ['work_report.update', '\u4fee\u6539\u8349\u7a3f\u6216\u9a73\u56de\u62a5\u544a'],
    ['work_report.delete', '\u5220\u9664\u8349\u7a3f\u6216\u9a73\u56de\u62a5\u544a'],
    ['work_report.submit', '\u63d0\u4ea4\u65e5\u62a5\u5468\u62a5'],
    ['work_report.review', '\u5ba1\u6838\u65e5\u62a5\u5468\u62a5'],
    ['work_report.manage_all', '\u7ba1\u7406\u5f53\u524d\u79df\u6237\u5168\u90e8\u65e5\u62a5\u5468\u62a5'],
    ['notification.read', '\u67e5\u770b\u901a\u77e5\u4e2d\u5fc3'],
    ['dashboard.read', '\u67e5\u770b\u5de5\u4f5c\u53f0\u548c\u6570\u636e\u770b\u677f'],
    ['image.read', '查看图片'],
    ['ai.image.generate', '调用 AI 生成图片'],
    ['ai.document.generate', '调用 AI 生成文档'],
    ['ai.web.search', '使用 AI 联网搜索公开资料'],
    ['dingtalk.integration.read', '查看钉钉企业绑定'],
    ['dingtalk.integration.manage', '管理钉钉企业绑定'],
    ['dingtalk.organization.read', '查看钉钉组织镜像'],
    ['dingtalk.organization.sync', '同步钉钉组织架构和人员'],
    ['dingtalk.organization.mapping.preview', '预览钉钉组织映射'],
    ['dingtalk.organization.mapping.manage', '应用钉钉组织映射'],
    ['assignment.policy.read', '查看分配策略'],
    ['assignment.policy.manage', '管理分配策略'],
    ['task.cross_functional.create', '创建跨职能任务'],
    ['task.cross_functional.read', '查看跨职能任务'],
    ['task.cross_functional.update', '修改跨职能任务'],
    ['task.cross_functional.delete', '删除跨职能任务'],
    ['task.cross_functional.status.update', '变更跨职能任务状态'],
    ['task.cross_functional.assignee.manage', '管理跨职能任务执行人'],
    ['task.cross_functional.comment.create', '新增跨职能任务评论'],
    ['task.cross_functional.comment.update', '修改跨职能任务评论'],
    ['task.cross_functional.comment.delete', '删除跨职能任务评论'],
    ['task.cross_functional.attachment.manage', '管理跨职能任务附件'],
    ['hr.profile.read', '查看员工档案'],
    ['hr.profile.manage', '管理员工档案'],
    ['hr.profile.sensitive.read', '查看员工敏感档案字段'],
    ['hr.profile.sensitive.manage', '管理员工敏感档案字段'],
    ['hr.leave.read', '查看请假记录'],
    ['hr.leave.request', '发起请假申请'],
    ['hr.leave.approve', '审批请假申请'],
    ['hr.leave.manage_all', '管理当前租户全部请假数据'],
    ['hr.attendance.read', '查看考勤记录'],
    ['hr.attendance.manage', '管理考勤记录'],
    ['hr.attendance.approve', '复核考勤异常'],
    ['hr.overtime.read', '查看加班申请'],
    ['hr.overtime.request', '发起加班申请'],
    ['hr.overtime.approve', '审批加班申请'],
    ['hr.employee_change.read', '查看人事异动'],
    ['hr.employee_change.manage', '管理人事异动'],
    ['hr.employee_change.approve', '审批人事异动'],
    ['hr.report.read', '查看人力资源报表'],
    ['finance.expense.read', '查看报销数据'],
    ['finance.expense.request', '发起报销申请'],
    ['finance.expense.approve', '审批报销申请'],
    ['finance.expense.manage_all', '管理当前租户全部报销数据'],
    ['legal.contract.read', '查看合同台账'],
    ['legal.contract.create', '创建合同台账'],
    ['legal.contract.update', '修改合同台账'],
    ['legal.contract.delete', '删除合同台账'],
    ['legal.contract.manage_all', '管理当前租户全部合同数据'],
] as const;

export const TENANT_ADMIN_ROLE_CODE = 'tenant_admin';

/** 新建租户角色时默认授予的 AI 能力权限：图片/文档的生成与查看。 */
export const DEFAULT_ROLE_PERMISSION_CODES = [
    'image.read',
    'document.read',
    'ai.image.generate',
    'ai.document.generate',
] as const;
